# Alternative Nixpacks configuration at root level
# Railway should prioritize this over auto-detection

[providers]
node = "18.20.4"

[phases.setup]
nixPkgs = ["nodejs_18", "postgresql"]

[phases.install]
cmds = [
  "npm ci --omit=dev --no-audit --no-fund",
  "npm cache clean --force"
]

[phases.build]
cmds = [
  "echo 'Root-level Nixpacks configuration applied successfully'"
]

[start]
cmd = "NODE_ENV=production PORT=$PORT node server.js"

[variables]
NODE_ENV = "production"
