# Railway Nixpacks Configuration - Simplified
# Focus on production optimization

[phases.install]
cmds = ["npm ci --omit=dev --no-audit --no-fund"]

[start]
cmd = "NODE_ENV=production node server.js"
