# Railway Nixpacks Configuration for Enhanced Futsal Booking System
# Optimized for Node.js/Express production deployment

[phases.setup]
nixPkgs = ["nodejs-18_x", "postgresql"]

[phases.install]
cmds = [
  "npm ci --omit=dev",
  "npm cache clean --force"
]

[phases.build]
cmds = [
  "echo 'Build phase completed - Node.js application ready'"
]

[start]
cmd = "NODE_ENV=production node server.js"

[variables]
NODE_ENV = "production"
PORT = "5000"
